In [1]:
#matrices 
#import numpy 
import numpy as np

In [2]:
#create matrix (2,2)
A=np.matrix([[2,6],[3,6]])
A

matrix([[2, 6],
        [3, 6]])

In [3]:
#create matrix (3,2) it has 3 elements 3rows and 2columns 
B=np.matrix([[2,4],[5,4],[7,-1]])
B

matrix([[ 2,  4],
        [ 5,  4],
        [ 7, -1]])

In [4]:
# let create row vector /kese
C=np.matrix([1,4,5,6])
C

matrix([[1, 4, 5, 6]])

In [5]:
# column vector /dik
D=np.matrix([[1],[8],[6],[-4]])
D

matrix([[ 1],
        [ 8],
        [ 6],
        [-4]])

###how to find size and order of matrices in numpy 

In [6]:
# A.shape gives us order of matrix 
A.shape

(2, 2)

In [7]:
B.shape 

(3, 2)

In [8]:
C.shape 

(1, 4)

In [9]:
D.shape 

(4, 1)

In [10]:
# .size number of elements in matrix 
#A=2*2=4
A.size 

4

In [11]:
B.size

6

In [12]:
C.size

4

In [13]:
D.size 

4